### ISSUE TITLE
What does this module do?

### ISSUE THREAD

**Issue by timwis** [Raynos/global#10]
Forgive me for a potentially elementary question, but I saw this module in use in the wild and couldn't figure out what it was for other than to satisfy linting errors. Coming upon the `README` didn't offer much more on the subject, so I thought I'd ask. And suggest perhaps putting the "why" in the `README`?

**Comment by Raynos** [comment]
The main use case is for running browser code in nodejs.

Suprisingly when using `min-document` to emulate various aspects of the DOM you can run most unit tests for frontend code in node. This means of running tests is far simpler and lighter then using phantom or spawning a browser to run your test suite.

**Comment by timwis** [comment]
Oh wow, I've been using [`jsdom-global`](https://github.com/rstacruz/jsdom-global) for that. This sounds much simpler! Thanks for the explanation. Do you think it's worth adding a note similar to your response to the readme? Or do most others get it?

**Comment by rstacruz** [comment]
Any plans on supporting other browser globals, such as `location`, `history`, and `navigator`? :)

(Btw, author of jsdom-global here!)

**Comment by Raynos** [comment]
I've since punted on supporting other things because I don't touch frontend anymore :P

I think it would be cool to have `node` compliant shims for other things so that unit tests can run, feel free to open a PR!

**Comment by ndugger** [comment]
I'd like to contribute to the repo; I'd love for it to export all references to globals in the DOM and Standard APIs. If that's something that would be in line with the goal of this package, let me know

**Comment by Raynos** [comment]
@ndugger 

I think this module is only for exposing browser globals that can be "mocked" in node.
A library can import this library so that the library can be tested in both a browser and nodejs and phantomjs, etc.
